version: '3.8'

services:
  orthanc:
    image: jodogne/orthanc:1.12.4
    ports:
      - "4242:4242"  # Port DICOM
      - "8042:8042"  # Port HTTP (interface web et API REST)
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro  # Configuration personnalisée
      - orthanc-storage:/var/lib/orthanc/db  # Stockage persistant
    environment:
      - ORTHANC__NAME=MediConnect-Orthanc
    restart: unless-stopped

volumes:
  orthanc-storage: