# Generated by Django 5.2 on 2025-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='médecin',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='médecin',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hôpital/Clinique'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Paris', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='Médicaments actuels'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Contact d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Téléphone d'urgence"),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], default='M', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='specialty',
            field=models.CharField(choices=[('CARDIOLOGIE', 'Cardiologie'), ('DERMATOLOGIE', 'Dermatologie'), ('GENERALISTE', 'Médecine générale'), ('RADIOLOGIE', 'Radiologie'), ('PEDIATRIE', 'Pédiatrie')], max_length=50, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de sécurité sociale'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
