# Generated by Django 5.2 on 2025-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hôpital_remove_médecin_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='orthanc_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Orthanc'),
        ),
    ]
