# Generated by Django 5.2 on 2025-04-25 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_orthanc_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hôpital',
            options={},
        ),
        migrations.AlterModelOptions(
            name='médecin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='rendezvous',
            name='unique_rendezvous_medecin_date',
        ),
        migrations.RemoveConstraint(
            model_name='rendezvous',
            name='unique_rendezvous_patient_date',
        ),
        migrations.AlterField(
            model_name='assistant',
            name='hôpital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hôpital'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='téléphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hôpital',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='hôpital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hôpital'),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='patients',
            field=models.ManyToManyField(related_name='médecins', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='specialty',
            field=models.CharField(choices=[('GENERALISTE', 'Médecine générale'), ('CARDIOLOGUE', 'Cardiologie'), ('DERMATOLOGUE', 'Dermatologie'), ('PEDIATRE', 'Pédiatrie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='médecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='orthanc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='médecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.médecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='reason',
            field=models.TextField(),
        ),
    ]
