# Generated by Django 5.2 on 2025-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dicomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dicom_images/'),
        ),
    ]
